spring:
  kafka:
    consumer:
      group-id: testbeat
      auto-offset-reset: earliest
      properties:
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="alice" password="alice-secret";
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: PLAIN
    bootstrap-servers: 192.168.0.163:9092
    producer:
      properties:
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="alice" password="alice-secret";
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: PLAIN
    admin:
      properties:
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="alice" password="alice-secret";
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: PLAIN

